"""Security Documentation Generator + Compliance Mapping (evidence mapping only — never a compliance claim)."""
from __future__ import annotations

import html
import json
import re
from typing import Any

import yaml

COMPLIANCE_MAP_VERSION = "compliance-map/1.0"
COMPLIANCE = {
    "MissingAuthentication": {"ISO/IEC 27001:2022": ["A.8.5"], "NIST SP 800-53 r5": ["IA-2", "IA-8"], "OWASP ASVS 4.0": ["V2"], "SOC 2": ["CC6.1"]},
    "MissingAuthorization": {"ISO/IEC 27001:2022": ["A.5.15", "A.8.3"], "NIST SP 800-53 r5": ["AC-3", "AC-6"], "OWASP ASVS 4.0": ["V4"], "SOC 2": ["CC6.1", "CC6.3"]},
    "UnvalidatedInputPath": {"ISO/IEC 27001:2022": ["A.8.26", "A.8.28"], "NIST SP 800-53 r5": ["SI-10"], "OWASP ASVS 4.0": ["V5"], "SOC 2": ["CC6.6"]},
    "MissingAudit": {"ISO/IEC 27001:2022": ["A.8.15"], "NIST SP 800-53 r5": ["AU-2", "AU-12"], "OWASP ASVS 4.0": ["V7"], "SOC 2": ["CC7.2"]},
    "SecurityControlGap": {"ISO/IEC 27001:2022": ["A.8.24", "A.8.20"], "NIST SP 800-53 r5": ["SC-8", "SC-7"], "OWASP ASVS 4.0": ["V9"], "SOC 2": ["CC6.7"]},
    "TrustBoundaryViolation": {"ISO/IEC 27001:2022": ["A.8.22", "A.5.14"], "NIST SP 800-53 r5": ["SC-7", "AC-4"], "OWASP ASVS 4.0": ["V1.4"], "SOC 2": ["CC6.6"]},
    "SensitiveDataEscape": {"ISO/IEC 27001:2022": ["A.8.12", "A.5.14"], "NIST SP 800-53 r5": ["AC-4", "SC-28"], "OWASP ASVS 4.0": ["V8"], "SOC 2": ["C1.1"]},
    "ExcessivePrivilege": {"ISO/IEC 27001:2022": ["A.8.2", "A.5.15"], "NIST SP 800-53 r5": ["AC-6"], "OWASP ASVS 4.0": ["V4.1"], "SOC 2": ["CC6.3"]},
    "DirectDatabaseAccess": {"ISO/IEC 27001:2022": ["A.8.22", "A.8.3"], "NIST SP 800-53 r5": ["AC-4", "SC-7"], "OWASP ASVS 4.0": ["V1.4"], "SOC 2": ["CC6.1"]},
    "UnsafeDataFanOut": {"ISO/IEC 27001:2022": ["A.8.11", "A.5.34"], "NIST SP 800-53 r5": ["SI-12"], "OWASP ASVS 4.0": ["V8"], "SOC 2": ["P4.1"]},
    "SecretExposurePath": {"ISO/IEC 27001:2022": ["A.8.24", "A.5.17"], "NIST SP 800-53 r5": ["IA-5", "SC-12"], "OWASP ASVS 4.0": ["V2.10", "V6"], "SOC 2": ["CC6.1"]},
    "UncontrolledThirdPartyFlow": {"ISO/IEC 27001:2022": ["A.5.19", "A.5.22"], "NIST SP 800-53 r5": ["SA-9", "CA-3"], "OWASP ASVS 4.0": ["V1.14"], "SOC 2": ["CC9.2"]},
    "PolicyConflict": {"ISO/IEC 27001:2022": ["A.5.15"], "NIST SP 800-53 r5": ["AC-3"], "OWASP ASVS 4.0": ["V4.1"], "SOC 2": ["CC6.1"]},
    "SeparationOfDutiesViolation": {"ISO/IEC 27001:2022": ["A.5.3"], "NIST SP 800-53 r5": ["AC-5"], "OWASP ASVS 4.0": ["V4.1"], "SOC 2": ["CC5.1"]},
}
PROPERTY_MAP = {"Confidentiality": ["SC-8", "SC-28"], "Integrity": ["SI-7", "SI-10"], "Authenticity": ["IA-2"], "LeastPrivilege": ["AC-6"],
                "SeparationOfDuties": ["AC-5"], "Traceability": ["AU-2"], "DataMinimization": ["SI-12"], "BoundaryEnforcement": ["SC-7", "AC-4"]}


def compliance_mapping(A: dict) -> dict:
    cats = {f["category"] for f in A["findings"]}
    rows = []
    for cat, fw in COMPLIANCE.items():
        rows.append({"category": cat, "findingsOpen": sum(1 for f in A["findings"] if f["category"] == cat), "frameworks": fw})
    return {"version": COMPLIANCE_MAP_VERSION, "notice": "This is an evidence mapping between THREADZERO assertions/findings and framework controls. "
            "It is NOT a statement of compliance; every mapping must be reviewed and validated by qualified assessors.",
            "categories": rows, "properties": [{"property": p["name"], "status": p["status"], "controls": PROPERTY_MAP.get(p["name"], [])} for p in A["properties"]],
            "openCategories": sorted(cats)}


def _t(rows: list[list[Any]], head: list[str]) -> str:
    esc = lambda x: str(x).replace("|", "\\|").replace("\n", " ")  # noqa: E731
    return "\n".join(["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"] + ["| " + " | ".join(esc(c) for c in r) + " |" for r in rows]) + "\n"


def mermaid_flow(A: dict, crossing_only: bool = False) -> str:
    lines = ["flowchart LR"]
    zones: dict[str, list[dict]] = {}
    for n in A["graph"]["nodes"]:
        zones.setdefault(n["zone"], []).append(n)
    for z in A["graph"]["zones"]:
        lines.append(f'  subgraph Z_{z["id"]}["{z["id"]} (trust {z["trust"]}, {z["kind"]})"]')
        for n in zones.get(z["id"], []):
            lines.append(f'    {n["id"]}["{n["id"]}<br/><small>{n["kind"]}</small>"]')
        lines.append("  end")
    for e in A["graph"]["edges"]:
        if crossing_only and not e["crossing"]:
            continue
        arrow = "==>" if e["crossing"] else "-->"
        style = "|" + ", ".join(e["data"]) + " · " + e["op"] + (" ⚠" if e["missing"] else "") + "|"
        lines.append(f'  {e["from"]} {arrow}{style} {e["to"]}')
    return "\n".join(lines)


def security_document(A: dict) -> str:
    p = A["project"]
    m = A["metrics"]
    sev = m["findingsBySeverity"]
    out = [f"# Architecture Security Document — {p['name']}", "", f"*Version {p['version']} · source hash `{A['sourceHash'][:12]}` · generated by THREADZERO {A['tool']['version']} ({A['tool']['ruleset']})*", "",
           "## 1. Summary", "", _t([[m["nodes"], m["flows"], m["zones"], m["dataTypes"], m["policies"], m["rules"], m["boundaryCrossings"]]],
                                    ["Nodes", "Flows", "Zones", "Data types", "Policies", "Rules", "Boundary crossings"]),
           "Findings by severity: " + ", ".join(f"**{k}** {v}" for k, v in sev.items()), "", "## 2. Trust zones", "",
           _t([[z["id"], z["trust"], z["kind"], z["maxClass"] or "—", ", ".join(n["id"] for n in A["graph"]["nodes"] if n["zone"] == z["id"])] for z in A["graph"]["zones"]], ["Zone", "Trust", "Kind", "Max class", "Nodes"]),
           "## 3. Data classification", "", _t([[d["name"], d["class"], d["rank"]] for d in A["symbols"]["data"]], ["Data type", "Class", "Rank"]),
           "## 4. Security properties", "", _t([[x["name"], x["status"], x["discharge"], ", ".join(x["findings"]) or "—"] for x in A["properties"]], ["Property", "Status", "Discharged by", "Findings"]),
           "## 5. Findings", "", _t([[f["id"], f["severity"], f["category"], f["message"], f["suggestedFix"]] for f in A["findings"]], ["ID", "Severity", "Category", "Evidence", "Suggested fix"]) if A["findings"] else "No findings.\n",
           "## 6. Assertions and constraints", "", _t([[a["name"], a["text"], a["status"], a["method"]] for a in A["assertions"]], ["Assertion", "Statement", "Status", "Method"]),
           _t([[c["name"], "satisfied" if c["satisfied"] else "UNSATISFIED"] for c in A["constraints"]], ["Constraint", "Status"]) if A["constraints"] else "",
           "## 7. Data-flow diagram", "", "```mermaid", mermaid_flow(A), "```", "", "## 8. Trust-boundary diagram", "", "```mermaid", mermaid_flow(A, True), "```", ""]
    return "\n".join(out)


def policy_catalog(A: dict) -> str:
    out = [f"# Policy Catalog — {A['project']['name']}", "", "Precedence: " + "priority ↓, scope specificity ↓, deny before allow, declaration order; first terminal match wins; default deny.", ""]
    out.append(_t([[r["idx"], r["id"], r["effect"], r["priority"], r["specificity"], f"`{r['condText']}`", ", ".join(r["obligations"]) or "—", r["reason"], f"{r['file']}:{r['line']}"] for r in A["policy"]["rules"]],
                  ["#", "Rule", "Effect", "Priority", "Scope", "Condition", "Obligations", "Reason", "Source"]))
    if A["policy"]["conflicts"]:
        out += ["## Conflicts", "", _t([[c["kind"], c["severity"], c["allow"], c["deny"], c["winner"], c["explain"]] for c in A["policy"]["conflicts"]], ["Kind", "Severity", "Allow", "Deny", "Winner", "Explanation"])]
    if A["policy"]["optimizations"]:
        out += ["## Optimization suggestions", "", _t([[o["kind"], ", ".join(o["rules"]), o["message"], o["proposal"]] for o in A["policy"]["optimizations"]], ["Kind", "Rules", "Message", "Proposal"])]
    return "\n".join(out)


def control_matrix(A: dict) -> str:
    groups = ["Authentication", "Authorization", "Encryption", "Validation", "Audit", "Monitoring", "Approval", "Isolation"]
    sym = {"satisfied": "✅", "missing": "❌", "extra": "➕", "n/a": "·"}
    rows = [[c["flow"], f"{c['from']} → {c['to']}", "yes" if c["crossing"] else "no"] + [sym[c["controls"][g]] for g in groups] for c in A["controlCoverage"]]
    return f"# Control Matrix — {A['project']['name']}\n\n✅ satisfied · ❌ required but missing · ➕ provided but not required · · not applicable\n\n" + _t(rows, ["Flow", "Path", "Crossing"] + groups)


def test_matrix(A: dict, tests: dict | None) -> str:
    out = [f"# Test Matrix — {A['project']['name']}", ""]
    kinds: dict[str, int] = {}
    for t in A["policy"]["tests"]:
        kinds[t["kind"]] = kinds.get(t["kind"], 0) + 1
    out.append(_t([[k, v] for k, v in sorted(kinds.items())], ["Generated test kind", "Count"]))
    if tests:
        out.append(_t([[s, v["passed"], v["failed"]] for s, v in tests["sections"].items()], ["Section", "Passed", "Failed"]))
    out.append(_t([[t["rule"], t["kind"], t["name"]] for t in A["policy"]["tests"][:200]], ["Rule", "Kind", "Test"]))
    return "\n".join(out)


def refactoring_report(A: dict, refactor: dict | None) -> str:
    out = [f"# Refactoring Report — {A['project']['name']}", ""]
    if not refactor:
        out.append("No refactoring session selected. Use `threadzero refactor <model> --finding F-001`.")
        return "\n".join(out)
    f = refactor["finding"]
    out += [f"**Finding {f['id']} — {f['category']} ({f['severity']})**", "", f["message"], ""]
    for c in refactor["candidates"]:
        out += [f"## Candidate {c['id']} — {c['title']}", "", c["description"], "",
                "**Preconditions:** " + "; ".join(f"{p['text']} ({'✔' if p['holds'] else '✘'})" for p in c["preconditions"]), "",
                "**Transformation:**", *[f"- {o}" for o in c["transformation"]], "",
                "**Postconditions:** " + "; ".join(f"{p['text']} ({'✔' if p['holds'] else '✘'})" for p in c["postconditions"]), "",
                f"**Security impact:** removed {len(c['securityImpact']['removed'])}, added {len(c['securityImpact']['added'])}, remaining {c['securityImpact']['remaining']}",
                f"**Functional impact:** equivalent={c['functionalImpact']['equivalent']}, added hops={c['functionalImpact']['addedHops']}",
                f"**Cost:** {c['cost']['newComponents']} new components, {c['cost']['rulesAdded']} rules, ≈{c['cost']['latencyEstimateMs']} ms latency (estimate)",
                "**Residual risk:** " + (", ".join(f"{r['severity']} {r['category']}" for r in c["residualRisk"]) or "none identified"), ""]
    return "\n".join(out)


def md_to_html(md: str, title: str = "THREADZERO report") -> str:
    body, lines, i = [], md.split("\n"), 0
    inline = lambda s: re.sub(r"`([^`]+)`", r"<code>\1</code>", re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", re.sub(r"\*([^*]+)\*", r"<i>\1</i>", html.escape(s))))  # noqa: E731
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("```"):
            lang, i, buf = ln[3:].strip(), i + 1, []
            while i < len(lines) and not lines[i].startswith("```"):
                buf.append(lines[i]); i += 1
            body.append(f'<pre class="{lang}"><code>{html.escape(chr(10).join(buf))}</code></pre>' if lang != "mermaid" else f'<pre class="mermaid">{html.escape(chr(10).join(buf))}</pre>')
        elif ln.startswith("|") and i + 1 < len(lines) and lines[i + 1].startswith("|--"):
            head = [c.strip() for c in ln.strip("|").split("|")]
            i += 2
            rows = []
            while i < len(lines) and lines[i].startswith("|"):
                rows.append([c.strip() for c in re.split(r"(?<!\\)\|", lines[i].strip().strip("|"))]); i += 1
            i -= 1
            body.append("<table><thead><tr>" + "".join(f"<th>{inline(h)}</th>" for h in head) + "</tr></thead><tbody>" + "".join("<tr>" + "".join(f"<td>{inline(c.replace(chr(92) + '|', '|'))}</td>" for c in r) + "</tr>" for r in rows) + "</tbody></table>")
        elif ln.startswith("#"):
            n = len(ln) - len(ln.lstrip("#"))
            body.append(f"<h{n}>{inline(ln[n:].strip())}</h{n}>")
        elif ln.startswith("- "):
            items = []
            while i < len(lines) and lines[i].startswith("- "):
                items.append(f"<li>{inline(lines[i][2:])}</li>"); i += 1
            i -= 1
            body.append("<ul>" + "".join(items) + "</ul>")
        elif ln.strip():
            body.append(f"<p>{inline(ln)}</p>")
        i += 1
    css = "body{font:15px/1.55 'Segoe UI',system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem;color:#1b1b1b}table{border-collapse:collapse;width:100%;margin:1rem 0;font-size:13px}th,td{border:1px solid #d0d0d0;padding:.35rem .55rem;text-align:left;vertical-align:top}th{background:#f3f3f3}code,pre{background:#f6f6f6;border-radius:4px;padding:.1rem .3rem}pre{padding:.7rem;overflow:auto}@media print{body{max-width:none}}"
    return f"<!doctype html><html><head><meta charset='utf-8'><title>{html.escape(title)}</title><style>{css}</style></head><body>{''.join(body)}</body></html>"


def export(kind: str, A: dict, fmt: str = "md", tests: dict | None = None, refactor: dict | None = None) -> tuple[str, str]:
    """Return (content, mime). kinds: security|policies|controls|tests|refactoring|compliance|dfd|tbd|all."""
    if kind == "compliance":
        data = compliance_mapping(A)
        md = "# Compliance Mapping (evidence only)\n\n> " + data["notice"] + "\n\n" + _t([[c["category"], c["findingsOpen"], "; ".join(f"{k}: {', '.join(v)}" for k, v in c["frameworks"].items())] for c in data["categories"]], ["Finding category", "Open", "Framework controls"])
    elif kind == "dfd":
        md = "# Data Flow Diagram\n\n```mermaid\n" + mermaid_flow(A) + "\n```\n"
    elif kind == "tbd":
        md = "# Trust Boundary Diagram\n\n```mermaid\n" + mermaid_flow(A, True) + "\n```\n"
    elif kind == "policies":
        md = policy_catalog(A)
    elif kind == "controls":
        md = control_matrix(A)
    elif kind == "tests":
        md = test_matrix(A, tests)
    elif kind == "refactoring":
        md = refactoring_report(A, refactor)
    elif kind == "all":
        md = "\n\n---\n\n".join([security_document(A), policy_catalog(A), control_matrix(A), test_matrix(A, tests), export("compliance", A, "md")[0]])
    else:
        md = security_document(A)
    data_obj = {"kind": kind, "project": A["project"], "findings": A["findings"], "properties": A["properties"], "rules": A["policy"]["rules"], "controlCoverage": A["controlCoverage"], "markdown": md}
    if fmt == "json":
        return json.dumps(data_obj, indent=1), "application/json"
    if fmt in ("yaml", "yml"):
        return yaml.safe_dump(json.loads(json.dumps(data_obj)), sort_keys=False, allow_unicode=True), "application/yaml"
    if fmt in ("html", "pdf"):
        return md_to_html(md, A["project"]["name"]), "text/html"
    return md, "text/markdown"
